name: 'CI Bot'
description: 'Combine PRs into staging branch 1 by 1'
inputs:
  gh_token:
    description: 'Github token'
    required: true  
  branch:
    description: 'Staging branch name'
    required: true      
  labels:
    description: 'Labels to exclude Separated_With_Underscores'
    required: false
    default: none
runs:
  using: 'node16'
  main: 'src/index.js'